name: Setup Heuristics Project (classic)
on:
  workflow_dispatch:

permissions:
  contents: read
  repository-projects: write   # <-- LAGAÐ

jobs:
  create-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: write   # <-- LAGAÐ
    steps:
      - name: Create Project (classic) if missing
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const projects = await github.rest.projects.listForRepo({ owner, repo });
            let project = projects.data.find(p => p.name === "Heuristics Board");
            if (!project) {
              const created = await github.rest.projects.createForRepo({
                owner, repo, name: "Heuristics Board", body: "Dálkar samsvara heuristics flokkum"
              });
              project = created.data;
            }

            async function ensureColumn(name) {
              const cols = await github.rest.projects.listColumns({ project_id: project.id });
              if (!cols.data.find(c => c.name === name)) {
                await github.rest.projects.createColumn({ project_id: project.id, name });
              }
            }

            const columns = [
              "Inbox",
              "Visibility & Feedback",
              "Match to real world",
              "User control & error prevention",
              "Consistency & standards",
              "Recognition over recall",
              "Flexibility & efficiency",
              "Aesthetics & minimalism",
              "In Review",
              "Done"
            ];
            for (const c of columns) await ensureColumn(c);
            core.info(`Project ready at: ${project.html_url}`);

